### ISSUE TITLE
Med Kits in Quickbelt break

### ISSUE THREAD

**Issue by Vatrasha** [Neocron-Classic/pre-release-issues#254]
Medical Kit in 10th Quick belt Slot lose functionality after death 
edit: probably an issue with the GR, not with death

They should keep the "loads" until they are used.

Put a Medical Kit in 10th Slot, die, respawn, (relog does not matter), the thing has no more uses and does not show a load number.
![Screenshot 2022-11-08 091352_quickbelt-med-kit](https://user-images.githubusercontent.com/14279967/200510401-2848ebf0-1533-4368-8e14-c58b6a2feb91.jpg)

**Comment by Vatrasha** [comment]
using a GR just broke the one in the 5th quick belt slot.

**Comment by Wilworin** [comment]
Know bug that have been reported before.

**Comment by NCC-Therenall** [comment]
@Wilworin I think I closed the old issue, assuming it was fixed with the item storage stuff (I hadn't been able to reproduce it locally when I did all of that.) So I'll leave this one up and tag it.

**Comment by Wilworin** [comment]
Oh, I thought you knew that it wasn't fixed. I have psi boosters break several times a day. :) All from quick belt so far. If anything, it actually got worse after the new item storage. Inventory corruption got worse after it was implemented as well. Or, that's my feeling atleast. :)

**Comment by NCC-Therenall** [comment]
@Wilworin Well to clarify, I knew it was broken from people in discord not too long after Phase 2 release. What I meant was the old issue I had closed, I closed back before Phase 2 when I finished the item storage changes internally. I couldn't reproduce them myself, so I thought it fixed it and closed the issue as "I think I fixed this in an upcoming patch".

**Comment by Jestunhi** [comment]
I closed the previous one (#34) as after testing I did not experience it again and after a week of no responses from anyone else to being asked if anyone was still experiencing it I marked it as closed.

This highlights the need for people to use this GitHub more. :)

**Comment by Vatrasha** [comment]
synaptic impairment is involved with this - just wrecked a medkit by rearranging skill points

**Comment by tuxhomer** [comment]
All usable item like medi kit, psi and stamina booster are brocken if you sync.
in side NC it works fine, but if you sync to/inside the canyon sectors and MB items will broke
